config/routes.rb
Rails.application.routes.draw do
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.save
    flash[:notice] = "#{@board.title}の掲示板を作りました"
    redirect_to boards_path
  end

  def show
    @board = Board.find(params[:id])
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    flash[:notice] = "編集しました"
    redirect_to board_path(@board)
  end

  def destroy
    board = Board.find(params[:id])
    board.delete
    flash[:notice] = "#{board.title}を削除しました"
    redirect_to boards_path
  end
  private

  def board_params
    params.require(:board).permit(:name, :title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/edit.html.slim
.ui.grid
  .two.column.row.title_header
    .column.title
      h3 掲示板編集
    .column.ui.right.aligned.header
      = link_to "掲示板一覧",boards_path, class: "ui button"
.ui.form
  = form_with model: @board, method: :patch do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :body
      = f.text_area :body
    = f.submit "編集", class: "ui blue button"

app/views/boards/index.html.slim
.ui.grid
  .two.column.row.title_header
    .column.title
      h3 掲示板一覧
    .column.ui.right.aligned.header
      = link_to "新規作成",new_board_path, class: "ui button"
table.ui.selectable.table
  thead
    tr
      th ID 
      th タイトル
      th 作成者
      th 作成日時
      th 更新日時 
      th
      th
  tbody
    - @boards.each do |board|
      tr
        td = board.id
        td = board.title
        td = board.name
        td = board.created_at.to_s(:datetime_jp)
        td = board.updated_at.to_s(:datetime_jp)
        td = link_to "詳細", board_path(board), class: "ui button"
        td = link_to "削除", board_path(board),method: :delete, data: {confirm: "#{board.title}を削除してもよろしですか？"}, class: "ui button"

app/views/boards/new.html.slim
.ui.grid
  .two.column.row.title_header
    .column.title
      h3 掲示板作成
    .column.ui.right.aligned.header
      = link_to "掲示板一覧",boards_path, class: "ui button"
.ui.form
  = form_with model: @board do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :body
      = f.text_area :body
    = f.submit "保存", class: "ui blue button"

app/views/boards/show.html.slim
.ui.grid
  .two.column.row.title_header
    .column.title
      h3 掲示板一覧
    .column.ui.right.aligned.header
      = link_to "編集",edit_board_path, class: "ui button"
.ui.segment
  .ui.segment
    .ui.grid
      .column
        = @board.title
  .ui.segment
    .ui.grid
      .column
        = @board.body
      .column
        = @board.name

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Myapp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .ui.container
      = yield